---
# tasks file for elastic
- name: install java
  apt:
    name: openjdk-8-jdk
    state: present

- name: add repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    
- name: install elk
  apt:
    name: ['elasticsearch', 'logstash', 'kibana']
    state: present

- name: put logstash configs
  template:
    src: "{{item}}.j2"
    dest: "/etc/logstash/conf.d/{{item}}.conf"
    owner: logstash
  with_items:
    - input
    - output
  notify:
  - restart logstash

- name: define kibana listen address
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^server\.host'
    line: 'server.host: "0.0.0.0"'
  notify:
    - restart kibana


- name: enable service ELK
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
    masked: no
  with_items:
    - 'elasticsearch'
    - 'logstash'
    - 'kibana'

